name: World-Manager
version: 1.0.0
author: hyperspace_pilot
main: de.hyper.worlds.domain.WorldManagement
api-version: 1.18
depend:
  - FastAsyncWorldEdit
commands:
  world:
    aliases:
      - worlds
      - welt
      - welten